services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:Z
    working_dir: /app   # 👈 ESSENCIAL para o uvicorn achar o main.py
    restart: always
    environment:
      - GEMINI_API_KEY=



  #frontend:
  #  build:
  #    context: ./frontend
  #  ports:
  #    - "3000:3000"
  #  volumes:
  #    - ./frontend:/app
  #  command: ["npm", "start"]
  #  restart: always
